StevenFiles/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('files/', include ('files.urls')),
    path('admin/', admin.site.urls),
]

files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:student_name>/', views.student, name='student'),
    path('<str:student_name>/files/<file_type>', views.file, name='file'),
]

files/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class File(models.Model):
    file = models.FileField(upload_to='provisional_files')
    file_type = models.CharField(max_length=200)
    belongs_to_student = models.ForeignKey('Student', on_delete=models.DO_NOTHING)
    timestamp = models.DateTimeField('date published')

    def __str__(self):
        return self.file_type

    def was_uploaded_recently(self):
        return self.timestamp >= timezone.now() - datetime.timedelta(days=1)

class Student(models.Model):
    name = models.CharField(max_length=300)
    age = models.IntegerField()
    country_of_citizenship = models.CharField(max_length=300)
    morningside_ID = models.IntegerField()
    sevis_ID = models.IntegerField()
    profile_picture = models.ImageField(upload_to="imgs")
    email = models.EmailField()
    major = models.CharField(max_length=300)
    status = models.CharField(max_length=300)
    graduation_year = models.IntegerField
    student_class = models.CharField(max_length=300)
    
    def __str__(self):
        return self.name
    
    

files/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, Http404

from .models import Student

# Create your views here.
def index(request):
    load_students = Student.objects.order_by('name')
    template = loader.get_template('files/index.html')
    context = {
        'load_students': load_students,
    }
    return HttpResponse(template.render(context, request))

def student(request, student_name):
    student = get_object_or_404(Student, pk=2)
    return render(request, 'files/student.html', {'student': student})

def file (request, student_id, file_type):
    return HttpResponse("You are looking at a file %s of student %s" % (file_type, student_id))

files/templates/files/index.html
<!--
<p>
    Current Students:
</p>
{% if load_students %}
    <ul>
    {% for student in load_students %}
        <li><a href={% url 'files:student' student.name%}>{{ student.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No students are available.</p>
{% endif %}
-->
<!-- Loading Static Content -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Students</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="{% static 'css/navstyle.css'%}">
		<link rel="stylesheet" href="{% static 'css/index.css'%}">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
	</head>
	<body>
		<header>
			<div class="col-12 topnav">
			<a class="active" href="#home">Home</a>
			<a href="/admin/">Admin</a>
			<a href="#contact">Contact Support</a>
			<a href="https://www.stevenmentor.com" target="_blank">Steven Mentor</a>
			</div> 
		</header>
		<h1> Steven Files </h1>
		<h3> Morningside College </h3>
		<p> Current Students </p>
		<ul id="Current">
			<li id="header">
				<span>ID</span>
				<span>Sudent Name</span>
				<span>Country of Citizenship</span>
				<span>Major</span>
				<span>Graduation Year</span>
				<span>Number of Files</span>
				<span>Completed Profile</span>
			</li>
			<li>
				<span class ="number">1</span>
				<span class ="name">Samuel Padilla</span>
				<span class="country">Colombia</span>
				<span class="major">Computer Science</span>
				<span class="year">2021</span>
				<span class="files">9</span>
				<span class="completed">Completed</span>
			</li>
			<li>
				<span class ="number">2</span>
				<span class ="name">Dean Stevens</span>
				<span class="country">Burkina Faso</span>
				<span class="major">Dance</span>
				<span class="year">2023</span>
				<span class="files">7</span>
				<span class="completed">Completed</span>
			</li>
			<li>
				<span class ="number">3</span>
				<span class ="name">Alex Popostov</span>
				<span class="country">Russia</span>
				<span class="major">Dance</span>
				<span class="year">2020</span>
				<span class="files">4</span>
				<span class="completed alert">Incomplete</span>
			</li>
			<li>
				<span class ="number">4</span>
				<span class ="name">Philips John</span>
				<span class="country">Mexico</span>
				<span class="major">Business</span>
				<span class="year">2021</span>
				<span class="files">12</span>
				<span class="completed">Completed</span>
			</li>
			<li>
				<span class ="number">5</span>
				<span class ="name">Daniel Luis</span>
				<span class="country">Argentina</span>
				<span class="major">Marketing</span>
				<span class="year">2021</span>
				<span class="files">3</span>
				<span class="completed alert">Incomplete</span>
			</li>
			<li>
				<span class ="number">6</span>
				<span class ="name">Mia Khalifa</span>
				<span class="country">Iran</span>
				<span class="major">Theatre</span>
				<span class="year">2021</span>
				<span class="files">6</span>
				<span class="completed">Completed</span>
			</li>
			<li>
				<span class ="number">7</span>
				<span class ="name">Luisa Freire</span>
				<span class="country">Brasil</span>
				<span class="major">Political Science</span>
				<span class="year">2023</span>
				<span class="files">5</span>
				<span class="completed">Completed</span>
			</li>
			<li>
				<span class ="number">8</span>
				<span class ="name">Andrea Rosales</span>
				<span class="country">Ecuador</span>
				<span class="major">Business</span>
				<span class="year">2021</span>
				<span class="files">2</span>
				<span class="completed alert">Incomplete</span>
			</li>
		</ul>

		<p> Prospective Students </p>
		<ul id="Prospect">
			<li id="header">
				<span>ID</span>
				<span>Sudent Name</span>
				<span>Country of Citizenship</span>
				<span>Major</span>
				<span>Graduation Year</span>
				<span>Number of Files</span>
				<span>Completed Profile</span>
			</li>
			<li>
				<span class ="number">1</span>
				<span class ="name">Andres Iniestas</span>
				<span class="country">Spain</span>
				<span class="major">Dance</span>
				<span class="year">2025</span>
				<span class="files">3</span>
				<span class="completed alert">Incomplete</span>
			</li>
			<li>
				<span class ="number">2</span>
				<span class ="name">Felipe Dos Santos</span>
				<span class="country">Brazl</span>
				<span class="major">Biology</span>
				<span class="year">2025</span>
				<span class="files">1</span>
				<span class="completed alert">Incomplete</span>
			</li>
			<li>
				<span class ="number">3</span>
				<span class ="name">Marco Rubio</span>
				<span class="country">Venezuela</span>
				<span class="major">Undecided</span>
				<span class="year">2025</span>
				<span class="files">4</span>
				<span class="completed alert">Incomplete</span>
			</li>
			<li>
				<span class ="number">4</span>
				<span class ="name">Pedro Tostes</span>
				<span class="country">Brazil</span>
				<span class="major">Undecided</span>
				<span class="year">2025</span>
				<span class="files">2</span>
				<span class="completed alert">Incomplete</span>
			</li>
		</ul>
	</body>
</html>

files/templates/files/student.html
<!--
<h1> {{student.name}} </h1>
<ul>
{% for file in student.file_set.all %}
    <li> {{ file.file_type }} </li>

{% endfor %}
</ul>
-->
<!--Load Static-->
{%load static%}
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> {{student.name}} </title>

    <link rel="stylesheet" href="{% static 'css/navstyle.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/student.css'%}" type="text/css">
    </head>
<body>
    <div class="container-fluid">
        <header>
            <div class="col-12 topnav">
            <a class="active" href='../'>Home</a>
            <a href="/admin/">Admin</a>
            <a href="#contact">Contact Support</a>
            <a href="https://www.stevenmentor.com" target="_blank">Steven Mentor</a>
            </div> 
        </header>

        <div class="row top-space">

            <div class="col-md-4 student-col">
        
                <h2>{{student.name}}</h2>
                <img src="https://via.placeholder.com/350x250">
                

                <ul>
                    <li> Country of Citizenship: {{student.country_of_citizenship}} </li>
                    <li> Age: {{student.age}} </li>
                    <li> Email: {{student.email}} </li>
                    <li> Major: {{student.major}} </li>
                    <li> Status: {{student.status}} </li>
                </ul>

            </div>
            
            <div class="col-md-8">

                <h2 class="file-head"> Files </h2> 
                
                <div class="row">
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                    <div class="col-md-4">
                        <p> This is a File </p>
                        <img src="https://via.placeholder.com/150x200">
                    </div>
                </div>
            
            </div>
        
        </div>    

    </div>
</body>
</html>